import * as XLSX from 'xlsx';
import JSZip from 'jszip';

function appendStyle(xml:string,collection:string,item:string,entry:string){
 let index=0;const pattern=new RegExp(`(<${collection}\\b[^>]*>)([\\s\\S]*?)(</${collection}>)`);
 if(!pattern.test(xml))throw new Error('Struktur format template tidak tersedia.');
 const next=xml.replace(pattern,(_match,open:string,body:string,close:string)=>{index=(body.match(new RegExp(`<${item}(?:\\s|>)`,'g'))||[]).length;const head=/count="\d+"/.test(open)?open.replace(/count="\d+"/,`count="${index+1}"`):open.replace('>',` count="${index+1}">`);return head+body+entry+close;});
 return {xml:next,index};
}
function layout(book:XLSX.WorkBook){
 for(const name of book.SheetNames){const sheet=book.Sheets[name];const range=XLSX.utils.decode_range(sheet['!ref']||'A1');
  if(name==='Costing Template')sheet['!cols']=[7,38,26,16,19,19,19,13,19,24,24,24,24,24,24,24,24,18,26,30].map(wch=>({wch}));
  else if(name==='Data Dasar RS')sheet['!cols']=[{wch:44},{wch:32}];
  else if(name==='Data Operasional')sheet['!cols']=[{wch:38},...Array.from({length:6},()=>({wch:25}))];
  sheet['!rows']=Array.from({length:range.e.r+1},(_,r)=>{const first=String(sheet[XLSX.utils.encode_cell({r,c:0})]?.v||'');if(name==='Costing Template')return {hpt:first==='No'?48:/^[ABC]\.\s*PUSAT/.test(first)||r===0?30:26};return sheet['!rows']?.[r]||{hpt:r===0?40:30};});
  if(name==='Costing Template'){sheet['!merges']=sheet['!merges']||[];for(let r=0;r<=range.e.r;r++){const text=String(sheet[XLSX.utils.encode_cell({r,c:0})]?.v||'');const last=r===0?8:range.e.c;if((r===0||/^[ABC]\.\s*PUSAT/.test(text))&&Array.from({length:last},(_,i)=>sheet[XLSX.utils.encode_cell({r,c:i+1})]?.v).every(v=>v==null||v==='')&&!sheet['!merges'].some(m=>m.s.r===r))sheet['!merges'].push({s:{r,c:0},e:{r,c:last}});}}
 }
}
/** Add presentation styles to the XLSX generated by the app, preserving values/formulas. */
export async function templateWorkbookBytes(book:XLSX.WorkBook){
 layout(book);const zip=await JSZip.loadAsync(XLSX.write(book,{type:'array',bookType:'xlsx'}));let xml=await zip.file('xl/styles.xml')!.async('string');
 const add=(collection:string,item:string,entry:string)=>{const next=appendStyle(xml,collection,item,entry);xml=next.xml;return next.index;};
 const font=add('fonts','font','<font><sz val="11"/><color rgb="FF14213D"/><name val="Arial"/></font>');
 const headerFont=add('fonts','font','<font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Arial"/></font>');
 const inputFont=add('fonts','font','<font><sz val="11"/><color rgb="FF1D4ED8"/><name val="Arial"/></font>');
 const navy=add('fills','fill','<fill><patternFill patternType="solid"><fgColor rgb="FF0B1F3A"/><bgColor indexed="64"/></patternFill></fill>');
 const yellow=add('fills','fill','<fill><patternFill patternType="solid"><fgColor rgb="FFFFF7DA"/><bgColor indexed="64"/></patternFill></fill>');
 const gray=add('fills','fill','<fill><patternFill patternType="solid"><fgColor rgb="FFF4F6FA"/><bgColor indexed="64"/></patternFill></fill>');
 const style=(fontId:number,fillId=0,numFmtId=0,horizontal='left')=>add('cellXfs','xf',`<xf numFmtId="${numFmtId}" fontId="${fontId}" fillId="${fillId}" borderId="0" xfId="0" applyFont="1" applyFill="1" applyNumberFormat="1" applyAlignment="1"><alignment horizontal="${horizontal}" vertical="top" wrapText="1"/></xf>`);
 const styles={body:style(font),header:style(headerFont,navy,0,'center'),input:style(inputFont,yellow),inputMoney:style(inputFont,yellow,4,'right'),formula:style(font,gray),formulaMoney:style(font,gray,4,'right'),note:style(font,gray)};
 zip.file('xl/styles.xml',xml);
 for(const [i,name] of book.SheetNames.entries()){
  const sheet=book.Sheets[name];const filename=`xl/worksheets/sheet${i+1}.xml`;let source=await zip.file(filename)!.async('string');
  source=source.replace(/<c\b([^>]*?)\br="([A-Z]+\d+)"([^>]*?)>/g,(_match,left:string,address:string,right:string)=>{
   const point=XLSX.utils.decode_cell(address);const cell=sheet[address];const first=String(sheet[XLSX.utils.encode_cell({r:point.r,c:0})]?.v||'');let id=styles.body;
   const guide=['Panduan Pengisian','Kamus Kolom','Contoh Pengisian'].includes(name);
   const header=point.r===0||(name==='Contoh Pengisian'&&point.r===1)||(name==='Costing Template'&&(first==='No'||/^[ABC]\.\s*PUSAT/.test(first)));
   const money=(name==='Costing Template'&&((point.c>=9&&point.c<=16)||point.c===18))||(name==='Aset'&&point.c===2)||(name==='Pengecualian'&&[1,2].includes(point.c));
   if(header)id=styles.header;else if(cell?.f)id=money?styles.formulaMoney:styles.formula;else if(guide)id=point.r%2===0?styles.note:styles.body;else if(name==='Costing Template'&&typeof sheet[XLSX.utils.encode_cell({r:point.r,c:0})]?.v==='number'&&point.c>=2&&point.c!==19)id=money?styles.inputMoney:styles.input;else if(name!=='Costing Template'&&point.r>0&&point.c>0)id=money?styles.inputMoney:styles.input;
   const selfClosing=/\/\s*$/.test(right);const attributes=right.replace(/\s+s="\d+"/g,'').replace(/\/\s*$/,'');
   return `<c${left.replace(/\s+s="\d+"/g,'')}r="${address}"${attributes} s="${id}"${selfClosing?'/':''}>`;
  });
  const headerRow=name==='Costing Template'?Object.keys(sheet).filter(k=>!k.startsWith('!')).map(k=>({cell:sheet[k],p:XLSX.utils.decode_cell(k)})).find(v=>v.p.c===0&&v.cell.v==='No')?.p.r??0:name==='Contoh Pengisian'?1:0;
  const rows=headerRow+1;const columns=name==='Costing Template'?2:0;
  source=source.replace(/<sheetViews>[\s\S]*?<\/sheetViews>/,`<sheetViews><sheetView workbookViewId="0" showGridLines="0"><pane ySplit="${rows}"${columns?` xSplit="${columns}"`:''} topLeftCell="${XLSX.utils.encode_cell({r:rows,c:columns})}" activePane="${columns?'bottomRight':'bottomLeft'}" state="frozen"/></sheetView></sheetViews>`);
  zip.file(filename,source);
 }
 return zip.generateAsync({type:'uint8array',compression:'DEFLATE'});
}
export async function downloadTemplateWorkbook(book:XLSX.WorkBook,filename:string){
 const bytes=await templateWorkbookBytes(book);const blob=new Blob([new Uint8Array(bytes)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=filename;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
