import {useState} from 'react';
import {Download,LockKeyhole,Upload,ShieldCheck} from 'lucide-react';
import {useV4Store} from './store';
import {download} from './reports';
import {validateFiles} from './security';
export function BackupPanel(){
  const state=useV4Store();const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [file,setFile]=useState<File|null>(null);const [replace,setReplace]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
  const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setMessage('');try{await fn();setPassword('');setConfirm('');}catch(e){setError(e instanceof Error?e.message:'Proses gagal.');}finally{setBusy(false);}};
  return <section className="uc-panel space-y-5"><div className="flex items-start gap-3"><div className="uc-icon"><ShieldCheck size={22}/></div><div><h2 className="text-lg font-semibold">Cadangan dan pemulihan</h2><p className="text-sm text-slate-500">Lindungi salinan data pasien dengan kata sandi yang Anda simpan sendiri.</p></div></div>
    <div className="uc-notice"><LockKeyhole size={18}/><p>Cadangan baru dienkripsi. Jika kata sandi hilang, salinan tersebut tidak dapat dipulihkan. Penyimpanan browser tetap berada pada perangkat ini dan belum dienkripsi.</p></div>
    <fieldset disabled={busy||state.busy} className="grid md:grid-cols-2 gap-5"><div className="uc-inset space-y-4"><h3 className="font-semibold">Buat cadangan</h3><label className="uc-label">Kata sandi cadangan<input type="password" autoComplete="new-password" className="uc-input" value={password} onChange={e=>setPassword(e.target.value)}/><span className="text-xs text-slate-500">Minimal 12 karakter. Tidak disimpan aplikasi.</span></label><label className="uc-label">Ulangi kata sandi<input type="password" autoComplete="new-password" className="uc-input" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button className="uc-primary" disabled={password.length<12||password!==confirm} onClick={()=>void run(async()=>{download(await state.backup(password),'UnitCost-Cadangan-Terenkripsi.json');setMessage('Cadangan terenkripsi berhasil diunduh.');})}><Download size={17}/>Unduh cadangan terenkripsi</button></div>
    <div className="uc-inset space-y-4"><h3 className="font-semibold">Pulihkan cadangan</h3><label className="uc-label">Berkas cadangan JSON<input className="uc-input" type="file" accept=".json" onChange={e=>{setFile(e.target.files?.[0]||null);setReplace(false);}}/></label><p className="text-sm text-slate-500">Gunakan kolom kata sandi di sebelah kiri untuk membuka cadangan terenkripsi. Cadangan lama tanpa enkripsi tetap dapat dibaca.</p><label className="flex gap-2 text-sm"><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>Saya memahami pemulihan mengganti data kerja dan versi hasil lokal. Saya sudah menyimpan salinan yang diperlukan.</label><button className="uc-secondary" disabled={!file||!replace} onClick={()=>void run(async()=>{validateFiles([file!],['json']);await state.restore(await file!.text(),password);setFile(null);setReplace(false);setMessage('Cadangan berhasil dipulihkan dan integritasnya diperiksa.');})}><Upload size={17}/>Pulihkan data</button></div></fieldset>
    {busy&&<p role="status">Memproses enkripsi dan pemeriksaan cadangan…</p>}{error&&<p className="uc-error" role="alert">{error}</p>}{message&&<p className="uc-success" role="status">{message}</p>}<p className="text-xs text-slate-500">{state.snapshots.length} versi hasil tersimpan. Kunci enkripsi tidak disimpan bersama berkas.</p>
  </section>;
}
