import {useRef,useState} from 'react';
import {UploadCloud,FileSpreadsheet,FileText,X,ShieldCheck} from 'lucide-react';
import {validateFiles} from './security';
export function FileDropzone({files,onChange,disabled}:{files:File[];onChange:(files:File[])=>void;disabled:boolean}){
  const input=useRef<HTMLInputElement>(null);const [drag,setDrag]=useState(false);const [error,setError]=useState('');
  const choose=(next:File[])=>{if(disabled)return;try{validateFiles(next);setError('');onChange(next);}catch(e){setError(e instanceof Error?e.message:'Berkas tidak valid.');}};
  return <div className="space-y-3"><div className={`uc-dropzone ${drag?'dragging':''}`} onDragOver={e=>{e.preventDefault();if(!disabled)setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);choose(Array.from(e.dataTransfer.files));}}><div className="uc-icon mx-auto"><UploadCloud size={24}/></div><h3>Tarik berkas ke sini, atau pilih dari perangkat</h3><p>Excel biaya RS (.xlsx, .xls) dan E-Klaim (.txt, .csv)</p><input ref={input} aria-label="File E-Klaim" className="sr-only" type="file" multiple accept=".txt,.csv,.xlsx,.xls" disabled={disabled} onChange={e=>{const next=Array.from(e.target.files||[]);if(next.length)choose(next);e.target.value='';}}/><button type="button" className="uc-secondary" disabled={disabled} onClick={()=>input.current?.click()}>Pilih berkas</button><small><ShieldCheck size={12}/>Diproses pada perangkat ini · maks. 250 MB per berkas</small></div>
    {files.length>0&&<ul className="uc-file-list" aria-label="Berkas terpilih">{files.map((f,i)=><li key={`${f.name}-${i}`}><div className="uc-icon">{/\.xlsx?$/i.test(f.name)?<FileSpreadsheet size={19}/>:<FileText size={19}/>}</div><div className="min-w-0 flex-1"><strong className="block truncate">{f.name}</strong><small>{(f.size/1024/1024).toFixed(2)} MB · {/\.xlsx?$/i.test(f.name)?'Biaya RS':'Data klaim'}</small></div><button aria-label={`Keluarkan ${f.name} dari pilihan`} disabled={disabled} onClick={()=>onChange(files.filter((_,n)=>n!==i))}><X size={16}/></button></li>)}</ul>}{error&&<p className="uc-error" role="alert">{error}</p>}
  </div>;
}
