import {displayDecimal} from './numbers';
import { useEffect,useState } from 'react';
import type { ReactNode } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { Link } from './Navigation';
import { useV4Store,activeSnapshot,canEdit } from './store';
import { KEYS,LABELS,EXPENSES,newCenter } from './types';
import type { Input,Center,Reference,Role,Method,Snapshot } from './types';
import { money,dec,parseNumber,maskSEP,sum } from './numbers';
import { monthsOf } from './engine';
import { importWorkbook,templateWorkbook,importReferences } from './imports';
import { download,exportExcel,exportPPT } from './reports';
import { usePreferences } from './preferences';
import { LOGIC_DEVELOPMENT,workingProfile,workflowSteps } from './workflow';
import { BackupPanel } from './BackupPanel';
import { validateFiles } from './security';
import {WorkspaceIntro,StartGuide} from './WorkspaceIntro';
import HospitalBaseRateResults from '../components/costing/HospitalBaseRateResults';
import {FileDropzone} from './FileDropzone';
import TemplateGuide from '../components/ui/TemplateGuide';
import {downloadTemplateWorkbook} from '../lib/templateWorkbookExport';
import {Calculator,CheckCircle2,AlertTriangle,Database,ArrowRight} from 'lucide-react';

const btn='uc-primary';
const secondary='uc-secondary';
const field='uc-input';
const detailPanels=new Set(['Kelola data aktif','Populasi pasien','Kelompok iDRG dan ketelitian sampel','Distribusi komponen dan jejak alokasi','Analisis sensitivitas','Asumsi dan sumber','Koreksi manual dan audit']);
function Panel({title,children}:{title:string;children:ReactNode}){return detailPanels.has(title)?<details className="uc-panel space-y-4"><summary className="font-semibold text-base">{title}</summary>{children}</details>:<section className="uc-panel space-y-4"><h2 className="font-semibold text-base">{title}</h2>{children}</section>;}
function Field({label,value,onChange,numeric=false,type='text',disabled=false}:{label:string;value:string;onChange:(v:string)=>void;numeric?:boolean;type?:string;disabled?:boolean}){
  const [local,setLocal]=useState({source:value,text:value});const draft=local.source===value?local.text:value;const [error,setError]=useState('');
  return <label className="block text-sm space-y-1"><span className="text-gray-600">{label}</span><input className={field} type={type} value={draft} disabled={disabled} onChange={e=>{setLocal({source:value,text:e.target.value});setError('');}} onBlur={()=>{try{const v=numeric&&draft!==''?parseNumber(draft):draft;if(v!==value)onChange(v);setLocal({source:v,text:v});}catch(e){setError(String(e));}}}/>{error&&<span className="text-red-700" role="alert">{error}</span>}</label>;
}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:(string|{value:string;label:string})[]}){return <label className="block text-sm space-y-1"><span className="text-gray-600">{label}</span><select className={field} value={value} onChange={e=>onChange(e.target.value)}>{options.map(v=>typeof v==="string"?<option key={v}>{v}</option>:<option key={v.value} value={v.value}>{v.label}</option>)}</select></label>;}
function Check({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/>{label}</label>;}
function Grid({children}:{children:ReactNode}){return <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{children}</div>;}
function Table({headers,rows}:{headers:string[];rows:ReactNode[][]}){const [query,setQuery]=useState('');const filtered=rows.filter(row=>row.some(v=>String(v??'').toLowerCase().includes(query.toLowerCase())));return <><label className="uc-label print:hidden">Cari isi tabel<input className="uc-input" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="uc-table-scroll" tabIndex={0} role="region" aria-label={`Tabel ${headers[0]}`}><table className="uc-table"><thead><tr>{headers.map((h,i)=><th scope="col" key={i}>{h}</th>)}</tr></thead><tbody>{filtered.length?filtered.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{typeof v==='string'&&['PROFIT','DEFISIT','BEP','Sampel rendah'].includes(v)?<span className={`uc-badge ${v==='PROFIT'?'success':v==='DEFISIT'?'error':'warning'}`}>{v}</span>:v}</td>)}</tr>):<tr><td className="uc-empty" colSpan={headers.length}>Belum ada data untuk ditampilkan.</td></tr>}</tbody></table></div><p className="text-xs text-slate-500">{filtered.length} / {rows.length} baris pada tabel ini. Filter tabel berlaku pada halaman yang ditampilkan.</p></>;}
function useActions(){const state=useV4Store();const w=state.workspace;const profile=w?workingProfile(w):undefined;const editable=Boolean(profile&&canEdit(profile.role));const [message,setMessage]=useState('');const act=async(fn:()=>void|Promise<void>)=>{try{setMessage('');await fn();}catch(e){setMessage(e instanceof Error?e.message:String(e));}};return {state,w,profile,editable,message,act};}

export function V4Header(){
  const navigate=useNavigate();const {pathname}=useLocation();
  const {state,w,profile,editable,message,act}=useActions();const snap=activeSnapshot(state);
  if(!w)return <p>Memuat data lokal…</p>;
  const stale=snap&&!snap.sensitivity&&snap.inputVersion!==w.version;
  const canCalculate=w.input.claims.length>0&&w.input.centers.some(c=>c.group==='final');
  return <div className="space-y-3 print:hidden uc-result-toolbar">
    <div className="flex flex-wrap gap-3 items-center justify-between"><div className="flex items-center gap-3"><Database size={19} className="text-teal-700"/><div><p className="text-xs font-semibold">{w.input.hospital||'Identitas RS belum diisi'}</p><p className="text-[11px] text-slate-500">{w.input.centers.length} pusat biaya · {w.input.claims.length.toLocaleString('id-ID')} klaim</p></div><span role="status" className={`uc-badge ${state.saving||state.error?.startsWith('Data sesi gagal')?'warning':'success'}`}>{state.saving?'Menyiapkan sesi…':state.error?.startsWith('Data sesi gagal')?'Data sesi bermasalah':'Sesi sementara'}</span></div>
      {!LOGIC_DEVELOPMENT&&<select aria-label="Profil lokal aktif" className="border rounded-lg p-2 text-sm max-w-full" value={w.activeProfile} disabled={state.busy} onChange={e=>void act(()=>state.selectProfile(e.target.value))}>{w.profiles.map(p=><option key={p.id} value={p.id}>{p.name} — {p.role}</option>)}</select>}</div>
    <div className="flex flex-wrap gap-3 items-center"><button className={btn} disabled={!editable||state.busy||!canCalculate} title={!canCalculate?'Unggah klaim dan tambahkan layanan final terlebih dahulu.':'Hitung dan simpan versi hasil baru'} onClick={()=>void act(async()=>{const before=useV4Store.getState().selected;await state.calculate();const after=useV4Store.getState();if(after.error)throw new Error(after.error);if(after.selected!==before)navigate(pathname.startsWith('/revisi4')?'/revisi4/dashboard':'/dashboard');})}><Calculator size={17}/>Hitung unit cost</button>{state.busy&&<><progress aria-label="Kemajuan proses" max="100" value={state.progress}/><span role="status" className="text-xs">Memproses {state.progress}%</span><button className={secondary} onClick={state.cancel}>Batalkan</button></>}
      <details><summary className="text-xs text-slate-500">Historis hasil</summary><label className="flex items-center gap-2 text-xs text-slate-500">Versi hasil<select aria-label="Versi hasil perhitungan" className="uc-input max-w-[300px]" value={state.selected||''} disabled={state.busy} onChange={e=>state.selectSnapshot(e.target.value)}><option value="">Belum ada hasil</option>{state.snapshots.filter(s=>!s.sensitivity).map(s=><option key={s.id} value={s.id}>{s.state} · {new Date(s.at).toLocaleString('id-ID')} · {s.id.slice(0,6)}</option>)}</select></label></details>
      {snap&&<span className={`uc-badge ${stale?'warning':snap.result.methods.some(m=>m.blocked)?'error':'neutral'}`}>{stale?<AlertTriangle size={13}/>:<CheckCircle2 size={13}/>} {stale?'Perlu dihitung ulang':snap.state}{snap.result.methods.some(m=>m.blocked)?' · Perlu perbaikan':''}</span>}
    </div>
    {!canCalculate&&<p className="text-xs text-slate-500">Mulai dengan <Link className="underline text-teal-700" to="/upload">unggah data</Link> dan isi pusat layanan final sebelum menghitung.</p>}
    {!LOGIC_DEVELOPMENT&&snap&&!stale&&!snap.sensitivity&&<div className="flex flex-wrap gap-2"><button className={secondary} disabled={!editable||snap.state!=='Draft'||snap.result.methods.some(m=>m.blocked)} onClick={()=>void act(()=>state.transition('Direview','Diajukan untuk review'))}>Ajukan review</button><button className={secondary} disabled={profile?.role!=='Reviewer'||snap.state!=='Direview'} onClick={()=>void act(()=>state.transition('Final','Disetujui reviewer'))}>Finalkan</button><button className={secondary} disabled={profile?.role!=='Reviewer'||snap.state!=='Direview'} onClick={()=>{const reason=window.prompt('Alasan penolakan');if(reason)void act(()=>state.transition('Draft',reason));}}>Tolak dengan alasan</button></div>}
    {(state.error||message)&&<p className="text-red-800 bg-red-50 p-3 rounded-lg" role="alert">{message||state.error}</p>}
    {stale&&<p className="bg-amber-50 text-amber-800 rounded-lg p-3 text-sm">Hasil di bawah berasal dari input versi {snap!.inputVersion}. Hitung ulang sebelum menggunakan hasil atau mengekspor laporan.</p>}
  </div>;
}
export function V4Page({view}:{view:string}){
  const state=useV4Store();const initialize=state.initialize;useEffect(()=>{void initialize();},[initialize]);
  if(!state.workspace)return <div className="space-y-3"><p>{state.error||'Memuat penyimpanan lokal…'}</p>{state.error&&<button className={btn} onClick={()=>void state.initialize()}>Coba lagi</button>}</div>;
  const step=workflowSteps.findIndex(s=>s.view===view);const next=view==='upload'?workflowSteps[1]:undefined;
  return <div className="space-y-6"><WorkspaceIntro view={view}/>{view!=='guide'&&<V4Header/>}{view==='guide'?<StartGuide/>:view==='input'?<CostInput/>:view==='upload'?<Upload/>:view==='settings'?<Settings/>:view==='reports'?<Reports/>:<Analysis view={view}/>} {step>=0&&next&&<div className="print:hidden flex justify-end"><Link className={btn} to={next.path}>Lanjut ke {next.label}<ArrowRight size={16}/></Link></div>}</div>;
}
function CostInput(){
  const {state,w,editable,message,act}=useActions();const input=w!.input;const [tab,setTab]=useState('Periode');const [advanced,setAdvanced]=useState(false);const [centerID,setCenterID]=useState(input.centers[0]?.id||'');const [pending,setPending]=useState<ReturnType<typeof importWorkbook>|null>(null);const [year,setYear]=useState('');
  const center=input.centers.find(c=>c.id===centerID)||input.centers[0];
  const update=(fn:(i:Input)=>Input,reason:string)=>void act(()=>state.update(fn,reason));
  const config=(key:string,value:unknown)=>update(i=>({...i,settings:{...i.settings,[key]:value}}),`Parameter ${key}`);
  const changeCenter=(patch:Partial<Center>)=>center&&update(i=>({...i,centers:i.centers.map(c=>c.id===center.id?{...c,...patch}:c),mappingVersion:patch.mapping?i.mappingVersion+1:i.mappingVersion,corrections:patch.mapping?[]:i.corrections}),`Unit ${center.name}`);
  const importExcel=async(file:File)=>{validateFiles([file],['xlsx','xls']);const result=importWorkbook(await file.arrayBuffer(),input);if(result.years.length>1){setPending(result);setYear(String(result.years[0]));}else{await state.importCosts(result.input,'Impor template biaya');setCenterID(result.input.centers[0]?.id||'');setPending(result);}};
  return <><TemplateGuide mode="integrated" compact/><InputDeletion/><Panel title="Input Biaya RS dan Distribusi 18 Variabel"><div className="flex flex-wrap gap-2"><label className={secondary}>Import Excel<input className="sr-only" type="file" accept=".xlsx,.xls" disabled={!editable||state.busy} onChange={e=>{const f=e.target.files?.[0];if(f)void act(()=>importExcel(f));e.target.value='';}}/></label><button className={secondary} onClick={()=>void act(()=>downloadTemplateWorkbook(templateWorkbook(input),'Template-Costing-Terintegrasi.xlsx'))}>Unduh template biaya terintegrasi</button></div>
    {pending&&<div className="bg-amber-50 p-3 rounded-lg text-sm space-y-2">{pending.warnings.map(t=><p key={t}>{t}</p>)}{pending.years.length>1&&<><select aria-label="Pilih tahun LK" value={year} onChange={e=>setYear(e.target.value)} className={field}>{pending.years.map(y=><option key={y}>{y}</option>)}</select><button className={btn} onClick={()=>void act(async()=>{await state.importCosts({...pending.input,settings:{...pending.input.settings,lkStart:`${year}-01-01`,lkEnd:`${year}-12-31`}},`Konflik tahun: memilih ${year}`);setPending(null);})}>Gunakan tahun ini</button></>}</div>}
    <div className="flex flex-wrap gap-2" role="tablist">{['Periode','Pusat biaya','Pemicu JKN','Matriks 18',...(input.settings.methods!=='M2'?['Driver antarunit']:[]),...(advanced?[...(input.settings.methods==='M2'?['Driver antarunit']:[]),'Cakupan','Koreksi']:[])].map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?btn:secondary} onClick={()=>setTab(t)}>{({'Pemicu JKN':'Porsi layanan JKN','Driver antarunit':'Pembagian antarunit','Matriks 18':'Komponen biaya'} as Record<string,string>)[t]||t}</button>)}</div><button className={secondary} onClick={()=>{setAdvanced(!advanced);if(advanced)setTab('Periode');}}>{advanced?'Tutup pengaturan lanjutan':'Pengaturan lanjutan'}</button><Link className={secondary} to="/settings">Referensi tarif dan asumsi</Link>
  </Panel>{message&&<p role="alert" className="text-red-700">{message}</p>}<fieldset disabled={!editable||state.busy} className="space-y-6">
    {tab==='Periode'?<Panel title="Periode biaya dan parameter alokasi"><Grid>
      <Field label="Nama RS" value={input.hospital} onChange={v=>update(i=>({...i,hospital:v}),'Identitas RS')}/>
      <Select label="Metode alokasi" value={input.settings.methods} options={[{value:'M2',label:'Metode 2: pool biaya bersama'},{value:'M1',label:'Metode 1: alokasi bertahap'},{value:'keduanya',label:'Bandingkan kedua metode'}]} onChange={v=>config('methods',v)}/>
      <Select label="Jenis biaya LK" value={input.settings.costType} options={['tahunan','periode']} onChange={v=>update(i=>({...i,settings:{...i.settings,costType:v as Input['settings']['costType'],costMonths:v==='tahunan'?'12':i.settings.costMonths}}),'Jenis biaya')}/>
      <Field label="Awal periode LK" type="date" value={input.settings.lkStart} onChange={v=>config('lkStart',v)}/><Field label="Akhir periode LK" type="date" value={input.settings.lkEnd} onChange={v=>config('lkEnd',v)}/>
      <Field label="Bulan cakupan biaya LK" numeric value={input.settings.costMonths} onChange={v=>config('costMonths',v)}/><Field label="Bulan klaim efektif (kosong = deteksi)" numeric value={input.settings.claimMonths} onChange={v=>config('claimMonths',v)}/>
    </Grid><details><summary className="font-medium text-sm">Asumsi periode dan pembagian tambahan</summary><Grid>
      <Select label="Keputusan periode berbeda" value={input.settings.periodDecision} options={['belum','proksi','harga']} onChange={v=>config('periodDecision',v)}/>
      <Field label="Pendapatan fungsional JKN (cadangan)" numeric value={input.settings.jknIncome} onChange={v=>config('jknIncome',v)}/><Field label="Pendapatan non-JKN (tanpa subsidi)" numeric value={input.settings.otherIncome} onChange={v=>config('otherIncome',v)}/>
      <Field label="Satuan driver pool bersama inap/jalan" value={input.settings.sharedUnit} onChange={v=>config('sharedUnit',v)}/><Field label="Driver pool bersama inap" numeric value={input.settings.sharedIn} onChange={v=>config('sharedIn',v)}/><Field label="Driver pool bersama jalan" numeric value={input.settings.sharedOut} onChange={v=>config('sharedOut',v)}/>
    </Grid><p className="text-sm text-gray-600">Faktor durasi = bulan klaim ÷ bulan biaya. Cadangan pembagian pool bersama memakai proporsi biaya langsung JKN jika driver tidak tersedia. Jangan mencampur hari rawat dengan kunjungan.</p></details></Panel>:tab==='Koreksi'?<Corrections/>:<>
      <Panel title="Pusat biaya"><div className="flex flex-wrap gap-2"><select aria-label="Pilih pusat biaya" value={center?.id||''} className={field+' max-w-lg'} onChange={e=>setCenterID(e.target.value)}><option value="">Pilih unit</option>{input.centers.map(c=><option key={c.id} value={c.id}>{c.name} ({c.group})</option>)}</select>{['overhead','intermediate','final'].map(g=><button key={g} className={secondary} onClick={()=>{const c=newCenter(g as Center['group']);update(i=>({...i,centers:[...i.centers,c]}),`Tambah ${g}`);setCenterID(c.id);}}>Tambah {g}</button>)}</div></Panel>
      {center&&tab==='Pusat biaya'&&<Panel title={center.name}><Grid><Field label="Nama pusat biaya" value={center.name} onChange={v=>changeCenter({name:v})}/><Select label="Kelompok" value={center.group} options={['overhead','intermediate','final']} onChange={v=>changeCenter({group:v as Center['group']})}/><Select label="Jenis rawat layanan" value={center.care} options={['inap','jalan','campuran']} onChange={v=>changeCenter({care:v as Center['care']})}/>{EXPENSES.map(k=><Field key={k} label={`Biaya ${k} selama LK`} numeric value={center.costs[k]} onChange={v=>changeCenter({costs:{...center.costs,[k]:v}})}/>)}<Field label="Biaya dikecualikan (basis periode LK)" numeric value={center.excluded} onChange={v=>changeCenter({excluded:v})}/><Field label="Nilai investasi gedung (umur 40 tahun)" numeric value={center.building} onChange={v=>changeCenter({building:v})}/></Grid><Check label="Penyusutan sudah tercakup pada biaya impor (aset tidak ditambah lagi)" value={center.depreciationIncluded} onChange={v=>changeCenter({depreciationIncluded:v})}/><h3 className="font-medium">Kelompok aset alat</h3>{center.assets.map(a=><div key={a.id} className="grid sm:grid-cols-4 gap-3"><Field label="Kelompok aset" value={a.name} onChange={v=>changeCenter({assets:center.assets.map(x=>x.id===a.id?{...x,name:v}:x)})}/><Field label="Nilai perolehan" numeric value={a.value} onChange={v=>changeCenter({assets:center.assets.map(x=>x.id===a.id?{...x,value:v}:x)})}/><Field label="Umur ekonomis tahun" numeric value={a.years} onChange={v=>changeCenter({assets:center.assets.map(x=>x.id===a.id?{...x,years:v}:x)})}/><button className={secondary} onClick={()=>changeCenter({assets:center.assets.filter(x=>x.id!==a.id)})}>Hapus aset</button></div>)}<div className="flex gap-2"><button className={secondary} onClick={()=>changeCenter({assets:[...center.assets,{id:crypto.randomUUID(),name:'Aset baru',value:'0',years:'5'}]})}>Tambah aset</button><button className={secondary} onClick={()=>{if(window.confirm(`Hapus ${center.name}?`))update(i=>({...i,centers:i.centers.filter(c=>c.id!==center.id)}),'Hapus unit');}}>Hapus unit</button></div><p className="text-sm text-gray-500">Overhead dialokasikan lebih dahulu, kemudian Intermediate. Penyusutan aset dihitung tahunan, disesuaikan dengan durasi LK, lalu periode klaim.</p></Panel>}
      {center&&tab==='Pemicu JKN'&&<Panel title="Pemicu pemisahan JKN"><Grid><Field label="Satuan volume (hari rawat, kunjungan, tes…)" value={center.driverUnit} onChange={v=>changeCenter({driverUnit:v})}/><Field label="Volume JKN" numeric value={center.jknVolume} onChange={v=>changeCenter({jknVolume:v})}/><Field label="Volume seluruh penjamin" numeric value={center.totalVolume} onChange={v=>changeCenter({totalVolume:v})}/><Field label="Volume JKN inap unit campuran" numeric value={center.inpatientVolume} onChange={v=>changeCenter({inpatientVolume:v})}/><Field label="Volume JKN jalan unit campuran" numeric value={center.outpatientVolume} onChange={v=>changeCenter({outpatientVolume:v})}/></Grid><p className="text-sm text-gray-600">Pemisahan memakai pemicu layanan final. Jika kosong, cadangan pendapatan ditandai. Volume inap/jalan unit campuran harus bersatuan sama.</p></Panel>}
      {center&&tab==='Driver antarunit'&&<Panel title="Driver penerima dan jejak step-down"><Field label="Satuan driver donor" value={center.allocationUnit} onChange={v=>changeCenter({allocationUnit:v})}/>{center.group==='final'?<p>Layanan final tidak mengalokasikan biaya keluar.</p>:<Grid>{input.centers.filter(c=>center.group==='overhead'?c.group!=='overhead':c.group==='final').map(c=><Field key={c.id} label={`Volume untuk ${c.name}`} numeric value={center.recipients[c.id]||''} onChange={v=>changeCenter({recipients:{...center.recipients,[c.id]:v}})}/>)}</Grid>}<p className="text-sm text-gray-600">Total volume unit penunjang saja tidak cukup; isi volume yang dipakai setiap penerima. Nol tidak dibagi otomatis.</p></Panel>}
      {center&&tab==='Matriks 18'&&<Panel title={`Matriks pemetaan versi ${input.mappingVersion}`}><p className="text-sm">Total baris: {sum(KEYS.map(k=>center.mapping[k])).toString()}% — harus 100%.</p>{center.group!=='final'?<p>Matriks diterapkan pada layanan final; donor dialokasikan melalui metode yang dipilih.</p>:<Grid>{KEYS.map((k,i)=><Field key={k} label={`${LABELS[i]} (%)`} numeric value={center.mapping[k]} onChange={v=>changeCenter({mapping:{...center.mapping,[k]:v}})}/>)}</Grid>}</Panel>}
      {center&&tab==='Cakupan'&&<Panel title="Cadangan biaya belum tercakup klaim"><Grid><Field label="Volume layanan JKN tercakup klaim" numeric value={center.coveredVolume} onChange={v=>changeCenter({coveredVolume:v})}/><Field label="Volume layanan JKN total" numeric value={center.coverageTotal} onChange={v=>changeCenter({coverageTotal:v})}/></Grid><p className="text-sm">Satuan dan periode harus sama dengan pemicu. Jika kosong, asumsi q=1 ditandai dan biaya pasien belum diklaim tidak dapat diidentifikasi.</p></Panel>}
    </>}
  </fieldset></>;
}
function Corrections(){
  const {state,w,profile,act,message}=useActions();const snap=activeSnapshot(state);const [method,setMethod]=useState<Method>('M2');const [care,setCare]=useState<'inap'|'jalan'>('inap');const [key,setKey]=useState<typeof KEYS[number]>('procedure_amt');const [value,setValue]=useState('0');const [reason,setReason]=useState('');
  return <Panel title="Koreksi komponen dengan alasan"><p className="text-sm">Koreksi harus merekonsiliasi pool JKN; sistem tidak menutup selisih substantif secara otomatis.</p><Grid><Select label="Metode" value={method} options={['M2','M1']} onChange={v=>setMethod(v as Method)}/><Select label="Jenis rawat" value={care} options={['inap','jalan']} onChange={v=>setCare(v as typeof care)}/><Select label="Komponen" value={key} options={[...KEYS]} onChange={v=>setKey(v as typeof key)}/><Field label="Nilai baru rupiah" numeric value={value} onChange={setValue}/><Field label="Alasan" value={reason} onChange={setReason}/></Grid><button className={btn} disabled={!snap||!reason.trim()} onClick={()=>void act(async()=>{const before=snap?.result.methods.find(m=>m.method===method)?.pools.find(p=>p.care===care)?.components[key];if(before===undefined)throw new Error('Hitung metode ini dahulu.');await state.update(i=>({...i,corrections:[...i.corrections,{id:crypto.randomUUID(),method,care,key,value,before,reason,actor:profile!.id,at:new Date().toISOString()}]}),'Koreksi komponen: '+reason);setReason('');})}>Catat koreksi dan hitung ulang</button>{message&&<p role="alert">{message}</p>}<Table headers={['Metode','Rawat','Komponen','Sebelum','Sesudah','Alasan']} rows={w!.input.corrections.map(c=>[c.method,c.care,c.key,money(c.before),money(c.value),c.reason])}/></Panel>;
}
function InputDeletion(){
  const {state,w,editable,act,message}=useActions();
  return <Panel title="Kelola data aktif"><p className="text-sm text-slate-500">Hapus klaim TXT atau biaya Excel secara terpisah. Versi laporan lama tetap tersimpan sebagai riwayat; hasil aktif perlu dihitung ulang.</p><div className="flex flex-wrap gap-3">{(['claims','costs'] as const).map(scope=><button key={scope} className={secondary} disabled={!editable||state.busy||state.saving||!(scope==='claims'?w!.input.claims.length:w!.input.centers.length)} onClick={()=>{if(window.confirm(scope==='claims'?'Hapus seluruh klaim aktif? Biaya RS dan versi laporan lama tetap tersimpan.':'Hapus seluruh pusat biaya aktif? Klaim TXT dan versi laporan lama tetap tersimpan.'))void act(()=>state.clearInput(scope));}}>{scope==='claims'?'Hapus data TXT / klaim':'Hapus data Excel / biaya RS'}</button>)}</div>{message&&<p role="alert" className="text-red-700">{message}</p>}</Panel>;
}
function Upload(){
  const {state,w,editable,act,message}=useActions();const [files,setFiles]=useState<File[]>([]);const claims=w!.input.claims;const [page,setPage]=useState(0);const issues=state.importIssues.length?state.importIssues:w!.input.importIssues||[];
  const [pending,setPending]=useState<{excel:ReturnType<typeof importWorkbook>;txt:File[]}|null>(null);const [year,setYear]=useState('');const [mode,setMode]=useState<'append'|'replace'>('append');const [reading,setReading]=useState(false);const [success,setSuccess]=useState('');const [warnings,setWarnings]=useState<string[]>([]);
  const apply=async(excel:ReturnType<typeof importWorkbook>|null,txt:File[],selectedYear?:string)=>{
    if(txt.length&&mode==='replace'&&useV4Store.getState().workspace!.input.claims.length&&!window.confirm('Ganti seluruh klaim aktif dengan TXT/CSV yang dipilih? Biaya RS tetap tersimpan.'))return;
    if(excel){const input=selectedYear?{...excel.input,settings:{...excel.input.settings,lkStart:`${selectedYear}-01-01`,lkEnd:`${selectedYear}-12-31`}}:excel.input;await state.importCosts(input,'Impor Excel biaya'+(selectedYear?`; memilih tahun ${selectedYear}`:''));setWarnings(excel.warnings);}
    if(txt.length){await state.upload(txt,mode);const after=useV4Store.getState();if(after.error)throw new Error(after.error);}
    setPage(0);setPending(null);setSuccess(`${excel?`Excel: ${excel.input.centers.length} pusat biaya berhasil dibaca. `:''}${txt.length?`TXT/CSV: ${useV4Store.getState().workspace!.input.claims.length.toLocaleString('id-ID')} baris berhasil dibaca.`:''}`);
  };
  const read=async()=>{
    setReading(true);setSuccess('');setWarnings([]);useV4Store.setState({error:''});try{validateFiles(files);const excelFiles=files.filter(f=>/\.xlsx?$/i.test(f.name));const txt=files.filter(f=>/\.(txt|csv)$/i.test(f.name));if(excelFiles.length+txt.length!==files.length)throw new Error('Format didukung: XLSX, XLS, TXT dan CSV.');if(excelFiles.length>1)throw new Error('Pilih satu template Excel biaya per unggahan; TXT/CSV boleh lebih dari satu.');const excel=excelFiles.length?importWorkbook(await excelFiles[0].arrayBuffer(),useV4Store.getState().workspace!.input):null;if(excel&&excel.years.length>1){setPending({excel,txt});setYear(String(excel.years[0]));return;}await apply(excel,txt);}finally{setReading(false);}
  };
  return <><TemplateGuide mode="integrated" compact/><InputDeletion/><Panel title="Upload Excel Biaya RS dan TXT E-Klaim"><p className="text-gray-600">Pilih satu template Excel biaya RS dan satu atau beberapa TXT/CSV E-Klaim. Keduanya boleh dipilih bersama atau diunggah terpisah. TXT/CSV menambah klaim secara bawaan; SEP duplikat mempertahankan baris yang sudah tersimpan. Excel memperbarui biaya RS tanpa menghapus klaim.</p><Select label="Cara memasukkan TXT/CSV" value={mode} options={[{value:"append",label:"Tambah ke klaim tersimpan"},{value:"replace",label:"Ganti seluruh klaim aktif"}]} onChange={v=>setMode(v as "append"|"replace")}/><FileDropzone files={files} disabled={!editable||state.busy||reading} onChange={next=>{setFiles(next);setPending(null);setSuccess('');}}/><button className={btn} disabled={!files.length||!editable||state.busy||reading||Boolean(pending)} onClick={()=>void act(read)}>{reading?'Memproses unggahan…':'Baca file'}</button>{pending&&<div className="bg-amber-50 p-3 rounded-lg space-y-3"><p>Tahun antarsheet berbeda: {pending.excel.years.join(', ')}. Pilih tahun biaya LK sebelum melanjutkan unggah.</p><Select label="Tahun biaya LK" value={year} options={pending.excel.years.map(String)} onChange={setYear}/><button className={btn} disabled={!editable||state.busy||reading} onClick={()=>void act(async()=>{setReading(true);try{await apply(pending.excel,pending.txt,year);}finally{setReading(false);}})}>Gunakan tahun dan lanjutkan unggah</button></div>}{success&&<p role="status" className="text-teal-800 bg-teal-50 p-3 rounded-lg">{success}</p>}{warnings.map(t=><p key={t} className="text-amber-800 text-sm">{t}</p>)}{message&&<p role="alert" className="text-red-700">{message}</p>}<p>{w!.input.centers.length} pusat biaya · {claims.length.toLocaleString('id-ID')} pasien · bulan unik: {monthsOf(claims).join(', ')||'Tanggal belum tersedia'}</p><Link className={secondary} to="/costing">Periksa biaya dan pemicu JKN</Link><p className="text-sm text-gray-500">Kode iDRG dibaca dari hasil grouping E-Klaim; aplikasi tidak melakukan grouper klinis baru. Tambahan kolom berisi “pending” atau “dispute” dikenali sebagai penanda.</p></Panel>
    {issues.length>0&&<Panel title="Kesalahan pembacaan"><p>{issues.length} baris perlu diperiksa.</p><Table headers={['File','Baris','Pesan']} rows={issues.slice(0,100).map(i=>[i.file,i.row,i.message])}/></Panel>}
    <Panel title="Populasi pasien"><Table headers={['SEP masking','Rawat','iDRG','Tanggal pulang','Billing','Pending','Dispute']} rows={claims.slice(page*50,page*50+50).map(p=>[maskSEP(p.sep),p.care,p.code,p.discharge,money(sum(Object.values(p.bill)).toString()),<input key="pending" aria-label={`Pending baris ${p.row}`} type="checkbox" disabled={!editable||state.busy} checked={p.pending} onChange={e=>void act(()=>state.update(i=>({...i,claims:i.claims.map(x=>x.id===p.id?{...x,pending:e.target.checked}:x)}),'Penanda pending'))}/>,<input key="dispute" aria-label={`Dispute baris ${p.row}`} type="checkbox" disabled={!editable||state.busy} checked={p.disputed} onChange={e=>void act(()=>state.update(i=>({...i,claims:i.claims.map(x=>x.id===p.id?{...x,disputed:e.target.checked}:x)}),'Penanda dispute'))}/>])}/><Pager page={page} count={claims.length} change={setPage}/></Panel></>;
}
function Pager({page,count,change}:{page:number;count:number;change:(p:number)=>void}){return <div className="flex gap-3 items-center print:hidden"><button className={secondary} disabled={page===0} onClick={()=>change(page-1)}>Sebelumnya</button><span className="text-sm">Halaman {page+1} dari {Math.max(1,Math.ceil(count/50))}</span><button className={secondary} disabled={(page+1)*50>=count} onClick={()=>change(page+1)}>Berikutnya</button></div>;}
function Settings(){
  const {state,w,profile,editable,act,message}=useActions();const input=w!.input;const [tab,setTab]=useState('Analisis');const [name,setName]=useState('');const [role,setRole]=useState<Role>('Analis');const [ref,setRef]=useState<Reference>({id:'',kind:'weight',adjustmentUnit:'factor',code:'',care:'inap',value:'1',from:'',until:'',version:'',source:'',verified:false});
  const config=(key:string,value:unknown)=>void act(()=>state.update(i=>({...i,settings:{...i.settings,[key]:value}}),`Pengaturan ${key}`));const admin=profile?.role==='Administrator';
  return <><Panel title="Pengaturan dan penyimpanan lokal"><div className="flex flex-wrap gap-2">{['Analisis','Referensi',...(!LOGIC_DEVELOPMENT?['Profil']:[]),'Cadangan'].map(t=><button className={tab===t?btn:secondary} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div><p className="text-sm text-gray-600">Fokus pengembangan: referensi, parameter perhitungan dan cadangan data lokal.</p></Panel>{message&&<p className="text-red-700" role="alert">{message}</p>}
    {tab==='Analisis'&&<fieldset disabled={!editable||state.busy}><Panel title="Toleransi, sampel, inflasi dan margin"><Grid><Select label="Basis toleransi" value={input.settings.toleranceMode} options={['persen','rupiah']} onChange={v=>config('toleranceMode',v)}/><Field label="Nilai toleransi (bawaan 5 persen)" numeric value={input.settings.tolerance} onChange={v=>config('tolerance',v)}/><Field label="Batas sampel rendah" numeric value={String(input.settings.sampleSize)} onChange={v=>config('sampleSize',Number(v))}/><p className="text-sm">Trimming: di luar rata-rata ±2 SD sampel (n−1), per iDRG dan jenis rawat; satu kali sebelum CW/Casemix/HBR.</p><Field label="Mark-up skenario (%)" numeric value={input.settings.markup} onChange={v=>config('markup',v)}/><Field label="Cost weight minimum" numeric value={input.settings.weightMin} onChange={v=>config('weightMin',v)}/><Field label="Cost weight maksimum" numeric value={input.settings.weightMax} onChange={v=>config('weightMax',v)}/><Field label="Selisih bulan harga (kosong = otomatis)" numeric value={input.settings.priceMonths} onChange={v=>config('priceMonths',v)}/><Field label="Ambang saran inflasi (bulan)" numeric value={input.settings.priceThreshold} onChange={v=>config('priceThreshold',v)}/></Grid><Check label="Aktifkan penyetaraan harga (penyusutan dikecualikan)" value={input.settings.priceActive} onChange={v=>config('priceActive',v)}/><Grid>{EXPENSES.filter(k=>k!=='penyusutan').map(k=><Field key={k} label={`Laju tahunan ${k} (%)`} numeric value={input.settings.inflation[k]} onChange={v=>config('inflation',{...input.settings.inflation,[k]:v})}/>)}</Grid><p className="text-sm text-gray-500">Laju dengan sumber dan tanggal berlaku dapat diimpor pada Referensi; nilai di sini menjadi cadangan lokal yang tercatat sebagai asumsi.</p></Panel></fieldset>}
    {tab==='Referensi'&&<Panel title="Referensi bertanggal berlaku"><fieldset disabled={!admin||state.busy} className="space-y-4"><Grid><Select label="Jenis referensi" value={ref.kind} options={['weight','base','adjustment','inflation']} onChange={v=>setRef({...ref,kind:v as Reference['kind']})}/><Field label="Kode iDRG / nama adjustment / jenis biaya" value={ref.code} onChange={v=>setRef({...ref,code:v})}/><Select label="Jenis rawat" value={ref.care} options={['inap','jalan','semua']} onChange={v=>setRef({...ref,care:v as Reference['care']})}/><Field label="Nilai (Adjustment Factor pengali; inflasi dalam %)" numeric value={ref.value} onChange={v=>setRef({...ref,value:v})}/><Field label="Berlaku mulai" type="date" value={ref.from} onChange={v=>setRef({...ref,from:v})}/><Field label="Berlaku sampai (opsional)" type="date" value={ref.until} onChange={v=>setRef({...ref,until:v})}/><Field label="Versi" value={ref.version} onChange={v=>setRef({...ref,version:v})}/><Field label="Sumber resmi / dokumen verifikasi" value={ref.source} onChange={v=>setRef({...ref,source:v})}/></Grid><Check label="Saya telah memverifikasi sumber dan tanggal berlaku (bukan angka ilustratif)" value={ref.verified} onChange={v=>setRef({...ref,verified:v})}/><button className={btn} onClick={()=>void act(async()=>{if(!ref.from||!ref.source.trim()||!ref.version.trim()||((ref.kind==='weight'||ref.kind==='adjustment')&&!ref.code.trim()))throw new Error('Lengkapi kode, sumber, versi dan tanggal.');await state.update(i=>({...i,references:[...i.references,{...ref,id:crypto.randomUUID()}]}),'Tambah versi referensi');setRef({...ref,id:'',verified:false});})}>Tambah versi referensi</button>
      <label className={secondary}>Import CSV referensi<input className="sr-only" type="file" accept=".csv" onChange={e=>{const f=e.target.files?.[0];if(f)void act(async()=>{const refs=importReferences(await f.text());await state.update(i=>({...i,references:[...i.references,...refs]}),'Impor referensi belum terverifikasi');});e.target.value='';}}/></label><button className={secondary} onClick={()=>download('kind,code,care,value,from,until,version,source\nweight,KODE_IDRG,inap,1,2025-01-01,,versi-contoh,Sumber ilustratif\n','Format-Referensi.csv','text/csv')}>Unduh format CSV</button></fieldset>
      <Table headers={['Jenis','Kode','Rawat','Nilai','Versi','Tanggal','Sumber','Verifikasi']} rows={input.references.map(r=>[r.kind,r.code,r.care,r.value+(r.kind==='adjustment'&&r.adjustmentUnit!=='factor'?' % (format lama)':''),r.version,`${r.from} – ${r.until||'seterusnya'}`,r.source,r.verified?'Terverifikasi':<button key={r.id} className={secondary} disabled={!admin||state.busy} onClick={()=>{if(window.confirm('Sumber dan masa berlaku referensi ini sudah diverifikasi? Angka ilustratif tidak boleh disetujui.'))void act(()=>state.update(i=>({...i,references:i.references.map(x=>x.id===r.id?{...x,verified:true}:x)}),'Verifikasi referensi '+r.version));}}>Belum terverifikasi</button>])}/><p className="text-sm">Impor selalu belum terverifikasi. Adjustment Factor bawaan 1 tanpa referensi tambahan; faktor lain harus memiliki sumber valid. Snapshot lama menyimpan versi referensi sendiri.</p></Panel>}
    {tab==='Profil'&&<Panel title="Profil alur kerja lokal"><fieldset disabled={!admin}><Grid><Field label="Nama pengguna lokal" value={name} onChange={setName}/><Select label="Peran" value={role} options={['Administrator','Analis','Reviewer','Pembaca']} onChange={v=>setRole(v as Role)}/></Grid><button className={btn} onClick={()=>void act(async()=>{await state.addProfile(name,role);setName('');})}>Tambah profil</button></fieldset><Table headers={['Nama','Peran']} rows={w!.profiles.map(p=>[p.name,p.role])}/><p className="text-sm">Reviewer tidak dapat menyetujui hasil yang ia buat atau koreksi. Pilihan profil ini bukan autentikasi multiuser server.</p></Panel>}
    {tab==='Cadangan'&&<BackupPanel/>}
  </>;
}
function Analysis({view}:{view:string}){
  const state=useV4Store();const snap=activeSnapshot(state);const [method,setMethod]=useState<Method>('M2');const [care,setCare]=useState('semua');const [query,setQuery]=useState('');const [status,setStatus]=useState('semua');const [pagination,setPagination]=useState({key:'',page:0});const [mdc,setMdc]=useState('');const [min,setMin]=useState('');const [max,setMax]=useState('');const mode=usePreferences(s=>s.viewMode);
  const filterKey=JSON.stringify([care,query,status,method,min,max,mdc,mode,snap?.id]);const page=pagination.key===filterKey?pagination.page:0;const setPage=(p:number)=>setPagination({key:filterKey,page:p});
  if(!snap)return <Panel title="Hasil perhitungan"><p>Lengkapi input biaya dan klaim, lalu pilih Hitung unit cost.</p><Link className={btn} to="/costing">Input biaya</Link></Panel>;
  const result=snap.result.methods.find(m=>m.method===method)||snap.result.methods[0];
  if(view==='patients')return <><Panel title="Hasil Pasien — Costing RS"><div className="flex flex-wrap gap-2">{snap.result.methods.map(m=><button key={m.method} className={result.method===m.method?btn:secondary} onClick={()=>setMethod(m.method)}>Metode {m.method}</button>)}</div><p className="text-sm">Versi hasil {snap.id.slice(0,8)} · {new Date(snap.at).toLocaleString('id-ID')}</p>{result.blocked&&<p role="alert" className="text-red-800">Metode ini memiliki validasi yang memblokir. Hasil diagnostik belum boleh digunakan.</p>}</Panel>{result.localCosting?<HospitalBaseRateResults result={result.localCosting} exportAllowed={!result.blocked && snap.inputVersion===state.workspace?.version}/>:<Panel title="CW dan HBR RS belum dihitung"><p>Snapshot lama memakai CW referensi. Hitung ulang untuk menyimpan CW RS dan HBR pada versi baru; riwayat lama tetap dipertahankan.</p><Link className={btn} to="/costing">Buka Biaya &amp; Alokasi</Link></Panel>}<Panel title="Rincian 18 komponen pasien"><Table headers={['SEP masking','Rawat','iDRG','Unit cost','Komponen alokasi']} rows={result.patients.slice(page*50,page*50+50).map(p=>[maskSEP(p.sep),p.care,p.code,money(p.uc),<details key={p.id}><summary>Lihat 18 komponen</summary>{KEYS.map((k,i)=><p key={k}>{LABELS[i]}: {money(p.allocations[k])}</p>)}</details>])}/><Pager page={page} count={result.patients.length} change={setPage}/></Panel></>;
  const patients=result.patients.filter(p=>{
    const delta=(mode==='IDRG'?p.tariffIDRG:p.tariffINA);const diff=delta===null?null:dec(delta).minus(p.uc);
    return (care==='semua'||p.care===care)&&(!mdc||p.mdc===mdc)&&(status==='semua'||(mode==='IDRG'?p.statusIDRG:p.statusINA)===status)&&`${p.code} ${p.inacbg} ${p.description} ${maskSEP(p.sep)}`.toLowerCase().includes(query.toLowerCase())&&(!min||(diff&&diff.gte(min)))&&(!max||(diff&&diff.lte(max)));
  });
  const titles:Record<string,string>={dashboard:'Dashboard Unit Cost',patients:'Biaya per pasien',comparison:'Perbandingan UC dan tarif'};
  return <><Panel title={titles[view]||'Hasil analisis'}><div className="flex flex-wrap gap-2">{snap.result.methods.map(m=><button key={m.method} className={result.method===m.method?btn:secondary} onClick={()=>setMethod(m.method)}>Metode {m.method}</button>)}</div><p className="text-sm">{snap.result.accepted.toLocaleString('id-ID')} klaim diterima · {snap.result.rejected.toLocaleString('id-ID')} ditolak · dihitung {new Date(snap.at).toLocaleString('id-ID')}</p>{result.blocked&&<p className="text-red-800" role="alert">Ada kesalahan yang memblokir metode ini. Hasil diagnostik belum boleh digunakan sebagai hasil final.</p>}
    <details><summary className="font-medium">Rincian rekonsiliasi biaya</summary><Table headers={['Rawat','Pool JKN','Alokasi pasien','Cadangan','Belum teralokasi','Tanpa weight','Casemix','CMI','Base rate RS']} rows={result.pools.map(p=>[p.care,money(p.total),money(p.allocated),money(p.reserve),money(p.unallocated),money(p.withoutWeight),p.casemix,p.cmi?dec(p.cmi).toFixed(4):'Tidak dapat dihitung',money(p.baseRate)])}/>
    {snap.result.methods.length>1&&<Table headers={['Metode','Biaya JKN','Alokasi','Belum teralokasi']} rows={snap.result.methods.map(m=>[m.method,money(m.total),money(sum(m.pools.map(p=>p.allocated)).toString()),money(sum(m.pools.map(p=>p.unallocated)).toString())])}/>}<p className="text-sm text-gray-600">Base rate memakai biaya pasien berweight valid. Biaya tanpa weight dan sisa tidak dimasukkan; simulasi RS bukan tarif pembayaran.</p></details>
  </Panel>
  {view==='dashboard'?<><Panel title="Filter ringkasan"><Grid><Select label="Jenis rawat" value={care} options={['semua','inap','jalan']} onChange={setCare}/><Field label="Cari kode, deskripsi atau SEP masking" value={query} onChange={setQuery}/></Grid><p className="text-sm">{patients.filter(p=>!p.outlier).length} inlier · {patients.filter(p=>p.outlier).length} outlier · biaya inlier {money(sum(patients.filter(p=>!p.outlier).map(p=>p.uc)).toString())}. Pool tetap memakai seluruh populasi unggahan.</p></Panel><div className="uc-metrics"><div className="uc-metric"><small>Total biaya JKN</small><strong>{money(result.total)}</strong></div><div className="uc-metric"><small>Biaya teralokasi ke pasien</small><strong>{money(sum(result.pools.map(p=>p.allocated)).toString())}</strong></div><div className="uc-metric"><small>Biaya belum teralokasi</small><strong>{money(sum(result.pools.map(p=>p.unallocated)).toString())}</strong></div></div><Panel title="Lanjutkan analisis"><div className="flex flex-wrap gap-3"><Link className={secondary} to="/tarif-pasien">Rincian pasien</Link><Link className={secondary} to="/compare">Bandingkan tarif</Link><Link className={btn} to="/reports">Unduh laporan</Link></div></Panel></>:<>
  <Panel title="Filter hasil"><Grid><Select label="Tarif pembanding" value={mode} options={[{value:'INACBG',label:'INA-CBG'},{value:'IDRG',label:'iDRG'}]} onChange={v=>usePreferences.getState().toggleViewMode(v as 'INACBG'|'IDRG')}/><Select label="Jenis rawat" value={care} options={['semua','inap','jalan']} onChange={setCare}/><Select label="Status" value={status} options={['semua','PROFIT','DEFISIT','BEP','Tidak dapat dihitung']} onChange={setStatus}/><Field label="Cari kode, diagnosis atau SEP masking" value={query} onChange={setQuery}/><Field label="MDC" value={mdc} onChange={setMdc}/><Field label="Selisih minimum rupiah" numeric value={min} onChange={setMin}/><Field label="Selisih maksimum rupiah" numeric value={max} onChange={setMax}/></Grid></Panel>
  <Panel title={'Unit cost dan tarif pembanding'}><Table headers={['SEP masking','Rawat','Kode','UC','Tarif '+mode,'Sumber','Selisih','Status','CRR','Simulasi RS','Target pasien','Penanda']} rows={patients.slice(page*50,page*50+50).map(p=>{
    const tariff=mode==='IDRG'?p.tariffIDRG:p.tariffINA;return [<details key={p.id}><summary>{maskSEP(p.sep)}</summary><dl>{KEYS.map((k,i)=><div key={k}>{LABELS[i]}: {money(p.allocations[k])}</div>)}</dl></details>,p.care,mode==='IDRG'?p.code:p.inacbg,money(p.uc),money(tariff),mode==='IDRG'?p.source:'E-Klaim',money(tariff?dec(tariff).minus(p.uc).toString():null),mode==='IDRG'?p.statusIDRG:p.statusINA,(mode==='IDRG'?p.crrIDRG:p.crrINA)?`${dec((mode==='IDRG'?p.crrIDRG:p.crrINA)!).mul(100).toFixed(2)}%`:'Tidak dapat dihitung',money(p.simulation),money(p.target),[p.pending?'Pending':'',p.disputed?'Dispute':'',p.outlier?'Outlier':''].filter(Boolean).join(', ')||'—'];})}/><Pager page={page} count={patients.length} change={setPage}/></Panel>
  <Panel title="Kelompok iDRG dan ketelitian sampel"><p className="text-sm">Statistik kelompok memakai inlier ±2 SD sampel (n−1). Biaya outlier tetap direkonsiliasi terpisah.</p><Table headers={['Rawat','iDRG','Kasus inlier','Mean UC','Median UC','Penanda']} rows={result.groups.filter(g=>(care==='semua'||g.care===care)&&g.code.toLowerCase().includes(query.toLowerCase())).slice(0,100).map(g=>[g.care,g.code,g.count,money(g.mean),money(g.median),g.lowSample?'Sampel rendah':'—'])}/></Panel>
  <Panel title="Distribusi komponen dan jejak alokasi"><Table headers={['Komponen','Inap','Jalan']} rows={KEYS.map((k,i)=>[LABELS[i],money(result.pools[0].components[k]),money(result.pools[1].components[k])])}/>{result.traces.length>0&&<Table headers={['Donor','Penerima','Driver','Satuan','Biaya']} rows={result.traces.slice(0,100).map(t=>[t.donor,t.recipient,t.driver,t.unit,money(t.amount)])}/>}</Panel>
  </>}<Validation snap={snap}/>{view==='comparison'&&<Sensitivity snap={snap}/>}</>;
}
function Validation({snap}:{snap:Snapshot}){
  const [code,setCode]=useState('semua');const [page,setPage]=useState(0);const errors=snap.result.issues.filter(i=>i.severity==='error');const filtered=snap.result.issues.filter(i=>code==='semua'||i.code===code);const counts=new Map<string,number>();snap.result.issues.forEach(i=>counts.set(i.code,(counts.get(i.code)||0)+1));
  const actions=[{path:'/costing',label:'Periksa biaya',codes:['V01','V02','V03','V08','V18','V19','V20','V22']},{path:'/upload',label:'Periksa data klaim',codes:['V04','V05','V11','V12']},{path:'/settings',label:'Periksa referensi',codes:['V06','V07','V16','V17','V23']}];
  return <Panel title="Pemeriksaan hasil"><p role="status">{errors.length?`${errors.length} masalah harus diperbaiki sebelum laporan dapat diunduh.`:snap.result.issues.length?'Perhitungan selesai. Ada catatan asumsi yang perlu ditinjau.':'Perhitungan selesai tanpa temuan validasi.'}</p>{errors.length>0&&<><ul className="list-disc pl-5 text-sm text-red-800">{[...new Set(errors.map(i=>i.message))].slice(0,5).map(t=><li key={t}>{t}</li>)}</ul><div className="flex flex-wrap gap-2">{actions.filter(a=>errors.some(i=>a.codes.includes(i.code))).map(a=><Link className={secondary} to={a.path} key={a.path}>{a.label}</Link>)}</div></>}<details><summary className="text-sm font-medium">Lihat semua catatan ({snap.result.issues.length})</summary><div className="space-y-4 mt-4"><Select label="Jenis catatan" value={code} options={['semua',...[...counts.keys()].sort()]} onChange={v=>{setCode(v);setPage(0);}}/><Table headers={['Kode','Tingkat','Metode','File/baris','Temuan']} rows={filtered.slice(page*50,page*50+50).map(i=>[i.code,i.severity,i.method||'semua',i.file?`${i.file}:${i.row}`:'—',i.message])}/><Pager page={page} count={filtered.length} change={setPage}/></div></details></Panel>;
}
function Sensitivity({snap}:{snap:Snapshot}){
  const {state,editable,act,message}=useActions();const [jkn,setJkn]=useState('');const [adj,setAdj]=useState('');const [inflation,setInflation]=useState('');const scenario=state.snapshots.find(s=>s.sensitivity&&s.previous===snap.id);
  return <Panel title="Analisis sensitivitas"><p className="text-sm">Skenario disimpan terpisah; input utama, hasil utama dan status persetujuannya tetap.</p><Grid><Field label="Rasio JKN seluruh layanan (%) opsional" numeric value={jkn} onChange={setJkn}/><Field label="Tambahan adjustment poin persen" numeric value={adj} onChange={setAdj}/><Field label="Laju inflasi seluruh biaya non-penyusutan (%)" numeric value={inflation} onChange={setInflation}/></Grid><button className={btn} disabled={!editable||state.busy} onClick={()=>void act(async()=>{const input=structuredClone(snap.input);if(jkn!==''&&(dec(jkn).lt(0)||dec(jkn).gt(100)))throw new Error('Rasio JKN 0–100%.');if(jkn!=='')input.centers.filter(c=>c.group==='final').forEach(c=>{c.driverUnit=c.driverUnit||'volume skenario';c.totalVolume='100';c.jknVolume=jkn;});if(adj!=='')input.references=input.references.map(r=>r.kind==='adjustment'?{...r,value:dec(r.value).plus(r.adjustmentUnit==='factor'?dec(adj).div(100):adj).toString()}:r);if(inflation!==''){input.settings.priceActive=true;input.settings.inflation={pegawai:inflation,jasaMedis:inflation,jasaLain:inflation,operasional:inflation,penyusutan:''};input.references=input.references.filter(r=>r.kind!=='inflation');}await state.calculate(input);})}>Hitung skenario terpisah</button>{message&&<p role="alert">{message}</p>}{scenario&&<Table headers={['Metode','Pool utama','Pool skenario','PROFIT','DEFISIT','BEP']} rows={scenario.result.methods.map(m=>[m.method,money(snap.result.methods.find(x=>x.method===m.method)?.total),money(m.total),m.patients.filter(p=>p.statusIDRG==='PROFIT').length,m.patients.filter(p=>p.statusIDRG==='DEFISIT').length,m.patients.filter(p=>p.statusIDRG==='BEP').length])}/>}</Panel>;
}
function Reports(){
  const {state,w,act,message}=useActions();const snap=activeSnapshot(state);if(!snap)return <Panel title="Laporan"><p>Hitung dan simpan hasil terlebih dahulu.</p></Panel>;
  const stale=snap.inputVersion!==w!.version;const blocked=snap.result.methods.some(m=>m.blocked);const allowed=!stale&&!blocked;
  return <><Panel title="Unduh laporan"><p>Hasil {snap.state} · {new Date(snap.at).toLocaleString('id-ID')}</p><p className="text-sm">Laporan Draft dan Direview diberi label status. Pada tahap pengembangan, gunakan laporan Draft untuk memeriksa hasil perhitungan.</p><div className="flex flex-wrap gap-2 print:hidden"><button className={btn} disabled={!allowed} onClick={()=>void act(()=>exportExcel(snap))}>Unduh Excel</button><button className={secondary} disabled={!allowed} onClick={()=>void act(()=>exportPPT(snap))}>Unduh PowerPoint</button><button className={secondary} disabled={!allowed} onClick={()=>window.print()}>Cetak / simpan PDF</button></div>{!allowed&&<p className="text-red-700">Ekspor ditahan: perbaiki validasi atau hitung ulang input.</p>}{message&&<p role="alert">{message}</p>}</Panel>
  {allowed&&snap.result.methods.map(m=>m.localCosting&&<Panel key={m.method} title={`HBR dan Casemix RS — ${m.method}`}><p>Sumber: {m.localCosting.source} · Periode {m.localCosting.period}. HBR bukan NBR; adjustment dasar 1.</p><Table headers={['Rawat','Kasus casemix',Number(m.localCosting!.schema)>=3?'Pool JKN penuh':'Biaya populasi rumus lama','Casemix RS','HBR','Tanpa kode','Biaya tanpa kode']} rows={m.localCosting.pools.map(p=>[p.care,p.count,money(p.total),displayDecimal(p.casemix),money(p.hbr),p.excludedCount,money(p.excludedCost)])}/></Panel>)}
  {allowed&&<><Panel title={`Ringkasan laporan ${snap.state}`}><h3>{snap.input.hospital}</h3><Table headers={['Metode','Rawat','Pool JKN','Cost pasien','Sisa','Base rate RS']} rows={snap.result.methods.flatMap(m=>m.pools.map(p=>[m.method,p.care,money(p.total),money(p.allocated),money(p.unallocated),money(p.baseRate)]))}/></Panel><Panel title="Asumsi dan sumber"><Table headers={['Parameter','Nilai']} rows={Object.entries(snap.input.settings).map(([k,v])=>[k,typeof v==='object'?JSON.stringify(v):String(v)])}/><Table headers={['Jenis','Kode','Versi','Tanggal','Sumber','Verifikasi']} rows={snap.input.references.filter(r=>snap.result.referenceIds.includes(r.id)).map(r=>[r.kind,r.code,r.version,r.from,r.source,r.verified?'Terverifikasi':'Ilustratif / belum terverifikasi'])}/></Panel><Panel title="Sumber tarif pembanding"><Table headers={['Metode','Sumber iDRG','Jumlah pasien']} rows={snap.result.methods.flatMap(m=>{const counts=new Map<string,number>();m.patients.forEach(p=>counts.set(p.source,(counts.get(p.source)||0)+1));return Array.from(counts,([source,count])=>[m.method,source,count]);})}/></Panel><Panel title="Ringkasan kelompok pasien"><Table headers={['Metode','Rawat','iDRG','Kasus','Mean UC','Median UC','Sampel rendah']} rows={snap.result.methods.flatMap(m=>m.groups.map(g=>[m.method,g.care,g.code,g.count,money(g.mean),money(g.median),g.lowSample?'Ya':'Tidak']))}/></Panel><Panel title="Koreksi manual dan audit"><Table headers={['Komponen','Sebelum','Sesudah','Alasan','Pengguna','Waktu']} rows={snap.input.corrections.map(c=>[c.key,money(c.before),money(c.value),c.reason,c.actor,c.at])}/><Table headers={['Pengguna','Tindakan','Waktu','Detail']} rows={snap.audit.map(a=>[a.actor,a.action,a.at,a.detail])}/></Panel><Validation snap={snap}/></>}
  </>;
}
