import {Link} from 'react-router-dom';
import {Check,ChevronRight,Upload,Calculator,SlidersHorizontal,Users,BarChart3,FileText,ArrowRight} from 'lucide-react';
import {useV4Store,activeSnapshot} from './store';
import {workflowSteps} from './workflow';
const copy:Record<string,{title:string;description:string}>={
  guide:{title:'Mulai analisis biaya RS',description:'Satu alur kerja, dari data sumber sampai laporan. Siapkan data, periksa asumsi, dan telusuri setiap hasil.'},
  upload:{title:'Unggah data sumber',description:'Masukkan Excel biaya dan TXT E-Klaim. Periksa hasil baca sebelum mulai menghitung.'},
  input:{title:'Periksa biaya dan alokasi',description:'Lengkapi periode, biaya langsung, pemicu JKN dan pemetaan komponen dalam satu tempat.'},
  settings:{title:'Atur referensi dan asumsi',description:'Gunakan referensi bertanggal yang dapat ditelusuri. Simulasi tetap terpisah dari tarif pembanding.'},
  patients:{title:'Hitung biaya per pasien',description:'Lihat alokasi 18 komponen, casemix, base rate dan biaya yang belum teralokasi.'},
  comparison:{title:'Bandingkan biaya dan tarif',description:'Telusuri sumber tarif, selisih biaya, status dan sensitivitas dari versi hasil yang sama.'},
  reports:{title:'Siapkan laporan analisis',description:'Ekspor hasil yang konsisten beserta asumsi, koreksi dan rekonsiliasi. Identitas SEP disamarkan.'},
  dashboard:{title:'Ringkasan analisis',description:'Pantau kesiapan data dan hasil terakhir sebelum mengambil keputusan.'},
};
export function WorkspaceIntro({view}:{view:string}){
  const state=useV4Store();const input=state.workspace!.input;const snap=activeSnapshot(state);const step=workflowSteps.findIndex(s=>s.view===view);const page=copy[view]||copy.dashboard;
  const ready=[input.claims.length>0,input.centers.some(c=>c.group==='final'),input.references.length>0,Boolean(snap),Boolean(snap),Boolean(snap)&&snap!.inputVersion===state.workspace!.version&&!snap!.result.methods.some(m=>m.blocked)];
  return <div className="space-y-5 print:hidden"><div className="uc-page-heading"><div><p className="uc-eyebrow">{step>=0?`TAHAP ${step+1} DARI 6`:'UNITCOST PRO'}</p><h1>{page.title}</h1><p>{page.description}</p></div><span className="uc-badge neutral">Pengembangan logika</span></div>{step>=0&&<nav aria-label="Tahapan kerja" className="uc-stepper">{workflowSteps.map((s,i)=><Link key={s.view} to={s.path} aria-current={s.view===view?'step':undefined} className={`uc-step ${s.view===view?'current':''}`}><span className="uc-step-number">{ready[i]&&i<step?<Check size={15}/>:i+1}</span><span>{s.label.replace(/^\d\. /,'')}</span>{i<5&&<ChevronRight size={15} className="uc-step-chevron"/>}</Link>)}</nav>}</div>;
}
export function StartGuide(){
  const w=useV4Store(s=>s.workspace)!;const icons=[Upload,Calculator,SlidersHorizontal,Users,BarChart3,FileText];const descriptions=['Excel biaya dan TXT/CSV klaim','Periode, pemicu JKN dan matriks biaya','Cost weight, adjustment dan inflasi','Distribusi UC dan rekonsiliasi','Sumber tarif dan simulasi terpisah','Excel, PowerPoint dan cetak PDF'];
  return <div className="space-y-5"><div className="uc-welcome"><div><p className="uc-eyebrow">MULAI DARI DATA YANG ANDA MILIKI</p><h2>Analisis yang lebih mudah ditelusuri.</h2><p>Ikuti enam tahap di bawah. Setiap perhitungan disimpan sebagai versi baru agar perubahan tetap dapat dibandingkan.</p><Link to="/upload" className="uc-primary">Mulai unggah data<ArrowRight size={17}/></Link></div><div className="uc-welcome-stats"><div><strong>{w.input.centers.length}</strong><span>Pusat biaya</span></div><div><strong>{w.input.claims.length.toLocaleString('id-ID')}</strong><span>Baris klaim</span></div></div></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{workflowSteps.map((s,i)=>{const Icon=icons[i];return <Link className="uc-guide-card" to={s.path} key={s.view}><div className="flex items-center justify-between"><div className="uc-icon"><Icon size={21}/></div><span className="text-xs font-semibold text-slate-400">TAHAP {i+1}</span></div><h3>{s.label.replace(/^\d\. /,'')}</h3><p>{descriptions[i]}</p><span className="uc-guide-arrow">Buka tahap<ArrowRight size={15}/></span></Link>;})}</div><details className="uc-panel"><summary className="cursor-pointer font-semibold">Cara kerja metode dan batas penggunaan</summary><div className="mt-4 text-sm text-slate-600 space-y-3"><p>Metode 1 mengalokasikan biaya Overhead dan Intermediate sebelum memisahkan JKN. Metode 2 menambahkan pool donor dengan rasio JKN tertimbang dari layanan final.</p><p>Data kerja browser belum dienkripsi. Profil lokal dan login pengembangan bukan autentikasi server. Gunakan data sintetis sampai kontrol akses produksi dan perlindungan penyimpanan diverifikasi.</p><p>Hasil pengembangan berstatus Draft. Simulasi RS dan mark-up tidak menggantikan tarif pembanding yang terverifikasi.</p></div></details></div>;
}
