import {useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import * as XLSX from 'xlsx';
import {Download,Info} from 'lucide-react';
import PageIntro from '../components/ui/PageIntro';
import {useCostingStore} from '../stores/costingStore';
import {neutralAdjustment} from '../lib/calculations/idrgTariff';
import {idrgPatientDetail,idrgDetailExport} from '../lib/calculations/idrgPatientDetails';
import {money,maskSEP} from '../v4/numbers';
export default function IDRGTariffPage(){
  const {tarifIDRGConfig:config,patientResults,rawRecords,rvuGlobalCosts,isProcessing}=useCostingStore();
  const [care,setCare]=useState('semua');const [query,setQuery]=useState('');const [page,setPage]=useState(0);
  const filtered=useMemo(()=>patientResults.filter(r=>(care==='semua'||(r.patient.ptd===1?'Inap':'Jalan')===care)&&`${r.patient.idrg?.drg_code||''} ${r.patient.inacbg} ${maskSEP(r.patient.sep)}`.toLowerCase().includes(query.toLowerCase())),[patientResults,care,query]);
  const safePage=Math.min(page,Math.max(0,Math.ceil(filtered.length/50)-1));const rows=filtered.slice(safePage*50,safePage*50+50).map(r=>({result:r,detail:idrgPatientDetail(r,config,Boolean(rvuGlobalCosts))}));
  const exportRows=()=>{const wb=XLSX.utils.book_new();for(const [name,values] of Object.entries(idrgDetailExport(filtered.map(r=>idrgPatientDetail(r,config,Boolean(rvuGlobalCosts))),config)))XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(values),name);XLSX.writeFile(wb,'Tarif-iDRG-per-Pasien.xlsx');};
  const comparison=(c:{difference:string|null;status:string})=><><strong>{money(c.difference)}</strong><small className="block mt-1">{c.status}</small></>;
  return <div className="max-w-[1600px] mx-auto space-y-6"><PageIntro title="Tarif iDRG per Pasien" what="Rincian Cost Weight × National Base Rate × Adjustment Factor, beserta unit cost RS dan perbandingan dengan tarif INA-CBG serta iDRG eksisting E-Klaim." result="Tiga pembanding tarif ditampilkan terpisah untuk setiap pasien."/>
    <section className="uc-panel space-y-4"><h1 className="text-xl font-bold">Rincian tarif dan unit cost per pasien</h1><p className="uc-notice"><Info size={18}/>Tarif iDRG rumus = CW × NBR × Adj Factor. NBR berasal dari Pengaturan menurut jenis rawat; nilai bawaan masih ilustratif sampai sumber nasional diverifikasi.</p><div className="grid sm:grid-cols-3 gap-4"><div className="uc-inset"><small>NBR Rawat Inap</small><p className="font-bold mt-1">{money(String(config.baseRateInap))}</p></div><div className="uc-inset"><small>NBR Rawat Jalan</small><p className="font-bold mt-1">{money(String(config.baseRateJalan))}</p></div><div className="uc-inset"><small>Adjustment Factor</small><p className="font-bold mt-1">{neutralAdjustment(config)}</p><small>Bawaan 1; pengali langsung.</small></div></div><Link className="uc-secondary" to="/settings">Ubah NBR dan Adj Factor</Link><p className="text-sm text-slate-500">Unit cost memakai hasil alokasi yang sama dengan analisis utama. Tarif iDRG eksisting dibaca dari total_tarif iDRG E-Klaim, bukan dari hasil rumus.</p>{!rvuGlobalCosts&&<p role="status" className="uc-notice">Biaya RS belum dialokasikan. Unit cost dan selisih terhadap UC belum dihitung; billing pasien tidak dianggap sebagai unit cost. <Link to="/tarif-pasien" className="underline">Lengkapi Cost per Pasien</Link></p>}</section>
    <section className="uc-panel space-y-4"><div className="flex flex-wrap items-end gap-4"><label className="uc-label">Jenis rawat<select className="uc-input" value={care} onChange={e=>{setCare(e.target.value);setPage(0);}}><option value="semua">Semua</option><option value="Inap">Rawat inap</option><option value="Jalan">Rawat jalan</option></select></label><label className="uc-label flex-1">Cari kode atau SEP masking<input className="uc-input" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label><button className="uc-secondary" disabled={!filtered.length||isProcessing} onClick={exportRows}><Download size={16}/>Ekspor rincian Excel</button></div><p className="text-sm">{filtered.length.toLocaleString('id-ID')} pasien · Selisih = tarif − unit cost. BEP menggunakan toleransi Rp 50.000, sama dengan analisis utama.</p>
      {isProcessing?<p role="status">Memperbarui hasil perhitungan…</p>:!patientResults.length?<p>{rawRecords.length?'Belum ada hasil pasien yang valid untuk ditampilkan.':'Belum ada data pasien.'} <Link to="/upload" className="underline text-teal-700">Periksa unggahan</Link></p>:<><div className="uc-table-scroll" tabIndex={0} role="region" aria-label="Rincian tarif iDRG per pasien"><table className="uc-table"><thead><tr>{['Pasien / rincian','Rawat','CW','NBR','Adj Factor','Tarif iDRG rumus','Unit cost RS','Tarif INA-CBG','Tarif iDRG eksisting','Rumus − UC','INA-CBG − UC','iDRG eksisting − UC','Rumus − iDRG eksisting'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(({detail:d,result:r},i)=><tr key={`${d.sep}-${safePage*50+i}`}><td><details><summary className="cursor-pointer">{d.sep}<span className="block text-xs mt-1">{d.code}</span></summary><dl className="min-w-64 mt-3 space-y-2"><div>iDRG: {d.code} · {r.patient.idrg?.drg_description||'—'}</div><div>INA-CBG: {d.inaCode}</div><div>CW: {d.cw??'Tidak tersedia'} · NBR: {money(d.nbr)} · Adj: {d.adj}</div><div>Rumus: {d.cw??'—'} × {d.nbr} × {d.adj}</div><div>NBR pada E-Klaim: {r.patient.idrg?.nbr>0?money(String(r.patient.idrg.nbr)):'Tidak tersedia'} (ditampilkan sebagai sumber asli)</div><div>Billing langsung: {money(String(r.biayaLangsung))}</div><div>Biaya tidak langsung: {rvuGlobalCosts?money(String(r.biayaTidakLangsung)):'Belum dialokasikan'}</div><div>Sumber NBR rumus: Pengaturan</div></dl></details></td><td>{d.care}</td><td>{d.cw??'Tidak tersedia'}</td><td>{money(d.nbr)}</td><td>{d.adj}</td><td>{money(d.formula)}</td><td>{d.unitCost===null?'Belum dihitung':money(d.unitCost)}</td><td>{money(d.existingINA)}</td><td>{money(d.existingIDRG)}</td><td>{comparison(d.comparisonFormula)}</td><td>{comparison(d.comparisonINA)}</td><td>{comparison(d.comparisonExisting)}</td><td>{money(d.formulaVsExisting)}</td></tr>)}</tbody></table></div><div className="flex items-center gap-3"><button className="uc-secondary" disabled={safePage===0} onClick={()=>setPage(safePage-1)}>Sebelumnya</button><span>{safePage+1} / {Math.max(1,Math.ceil(filtered.length/50))}</span><button className="uc-secondary" disabled={(safePage+1)*50>=filtered.length} onClick={()=>setPage(safePage+1)}>Berikutnya</button></div></>}
    </section></div>;
}
