import {useState} from 'react';
import {Link} from 'react-router-dom';
import {BookOpen,ArrowRight,CheckCircle2} from 'lucide-react';
import {getSheetGuides,templateRules,templateChecklist} from '../../lib/templateGuidance';
import type {TemplateMode} from '../../lib/templateGuidance';

export default function TemplateGuide({mode,compact=false}:{mode:TemplateMode;compact?:boolean}){
 const guides=getSheetGuides(mode);const [selected,setSelected]=useState('Mulai');const [query,setQuery]=useState('');const [checked,setChecked]=useState<number[]>([]);
 const guide=guides.find(g=>g.name===selected);const path=mode==='integrated'?'/revisi4':'';
 const fields=guide?.fields.filter(f=>`${f.name} ${f.unit} ${f.instruction}`.toLowerCase().includes(query.toLowerCase()))||[];
 const content=<div className="space-y-5 mt-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="uc-eyebrow">PANDUAN TEMPLATE EXCEL</p><h2 className="text-xl font-semibold">Isi template satu sheet demi satu sheet</h2><p className="text-sm text-slate-600 mt-2">{mode==='integrated'?'Analisis Biaya Terintegrasi':'Analisis 18 Komponen'} · contoh sintetis untuk membantu pengisian.</p></div><Link className="uc-secondary" to={`${path}/costing`}>Buka tempat unduh template<ArrowRight size={16}/></Link></div>
 <div className="uc-notice">Excel berisi biaya dan volume RS. TXT berisi rincian billing serta kode iDRG dari E-Klaim. Aplikasi mengalokasikan biaya RS ke pasien; angka billing bukan unit cost.</div>
 <nav aria-label="Pilih sheet panduan" className="flex gap-2 flex-wrap">{['Mulai',...guides.map(g=>g.name),'Cek sebelum unggah'].map(name=><button type="button" key={name} aria-pressed={selected===name} className={selected===name?'uc-primary':'uc-secondary'} onClick={()=>{setSelected(name);setQuery('');}}>{name}</button>)}</nav>
 {selected==='Mulai'&&<><div className="grid sm:grid-cols-3 gap-3">{[{title:'1. Siapkan sumber',text:'Ambil biaya dari keuangan, volume dari statistik pelayanan, dan nilai aset dari register aset.'},{title:'2. Isi Excel',text:'Mulai dari identitas, lalu unit dan biaya. Lengkapi penjamin serta sheet tambahan sesuai ruang analisis.'},{title:'3. Unggah dan periksa',text:'Pilih Excel dan TXT. Cocokkan jumlah baris, unit, tahun, bulan klaim, dan seluruh peringatan sebelum menghitung.'}].map(item=><div key={item.title} className="uc-inset space-y-2"><h3 className="font-semibold">{item.title}</h3><p className="text-sm text-slate-600">{item.text}</p></div>)}</div><h3 className="font-semibold">Aturan mengisi angka dan struktur</h3><ul className="space-y-3 text-sm text-slate-600">{templateRules.map(v=><li className="flex gap-2" key={v}><CheckCircle2 size={16} className="shrink-0 mt-0.5 text-teal-700"/>{v}</li>)}</ul><div className="uc-inset"><h3 className="font-semibold mb-2">Bedakan tiga kelompok unit</h3><p className="text-sm text-slate-600">Overhead: administrasi, keamanan, dan pendukung umum. Intermediate: laboratorium, radiologi, dan penunjang medis. Final: ruang rawat inap, rawat jalan, serta layanan pasien. Tempatkan tiap unit berdasarkan organisasi dan aktivitas RS; nama unit tidak selalu menentukan pemetaan otomatis.</p></div></>}
 {guide&&<section className="space-y-4" aria-label={`Petunjuk ${guide.name}`}><div><h3 className="font-semibold text-lg">{guide.name}</h3><p className="text-sm text-slate-600 mt-1">{guide.purpose}</p><p className="text-xs text-slate-500 mt-2">Sumber data: {guide.source}</p></div><p className="uc-notice">{guide.note}</p><label className="uc-label block">Cari kolom atau istilah<input className="uc-input mt-1" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Contoh: hari rawat, nilai alat, periode"/></label><div className="space-y-3">{fields.map(f=><article className="uc-inset grid md:grid-cols-[220px_1fr] gap-3" key={f.name}><div><h4 className="font-semibold text-sm">{f.name}</h4><p className="text-xs text-slate-500 mt-1">Satuan: {f.unit}</p></div><div><p className="text-sm text-slate-600">{f.instruction}</p><p className="mt-2 text-sm"><span className="font-semibold">Contoh isi:</span> <span className="font-mono break-words">{f.example}</span></p></div></article>)}{!fields.length&&<p role="status" className="text-sm text-slate-500">Kolom tidak ditemukan. Coba kata lain atau pilih sheet yang sesuai.</p>}</div><p className="text-xs text-slate-500">Contoh isi hanya menjelaskan bentuk data. Angka dan porsi sebenarnya diambil dari sumber RS.</p></section>}
 {selected==='Cek sebelum unggah'&&<section className="space-y-4"><h3 className="font-semibold">Pemeriksaan pribadi sebelum unggah</h3><p role="status" className="text-sm text-slate-600">{checked.length} dari {templateChecklist.length} hal telah Anda tandai. Daftar ini tidak menggantikan validasi aplikasi.</p><div className="space-y-3">{templateChecklist.map((text,i)=><label key={text} className="uc-inset flex items-start gap-3 cursor-pointer"><input className="mt-1" type="checkbox" checked={checked.includes(i)} onChange={e=>setChecked(e.target.checked?[...checked,i]:checked.filter(n=>n!==i))}/><span className="text-sm">{text}</span></label>)}</div><Link className="uc-primary" to={`${path}/upload`}>Buka Upload Data<ArrowRight size={16}/></Link></section>}
 <details className="uc-inset"><summary className="font-semibold cursor-pointer">Jika hasil unggah belum sesuai</summary><dl className="text-sm space-y-3 mt-3"><div><dt className="font-semibold">Pusat biaya tidak terbaca</dt><dd className="text-slate-600">Periksa nama sheet Costing Template, judul kelompok A/B/C, kolom No, dan Nama Unit. Unggah satu Excel setiap kali.</dd></div><div><dt className="font-semibold">Jumlah pasien nol atau TXT gagal</dt><dd className="text-slate-600">Gunakan ekspor TXT E-Klaim asli. Periksa struktur kolom, baris yang ditolak, serta format file. Jangan menyusun ulang kolom TXT melalui Excel.</dd></div><div><dt className="font-semibold">Biaya atau HBR nol/tidak dapat dihitung</dt><dd className="text-slate-600">Periksa biaya RS, periode, billing penerima, dan kode iDRG. Pada ruang terintegrasi periksa juga pemicu JKN serta matriks. Total biaya nol tidak menghasilkan CW/HBR yang valid.</dd></div><div><dt className="font-semibold">Tahun biaya dan klaim berbeda</dt><dd className="text-slate-600">Periksa apakah salah memilih file atau memang memakai biaya tahun berbeda. Jangan mengubah tahun hanya untuk menghilangkan peringatan.</dd></div></dl></details>
 </div>;
 return compact?<details className="uc-panel print:hidden"><summary className="font-semibold cursor-pointer flex gap-2 items-center"><BookOpen size={18}/>Bantuan pengisian template Excel</summary>{content}</details>:<section className="uc-panel" aria-label="Panduan pengisian template Excel">{content}</section>;
}
